import type { Coupon } from "./types";

export const site = {
  nameBn: "হাঁড়ির স্বাদ",
  nameEn: "Taste of Bogura",
  taglineBn: "ঐতিহ্যের আসল স্বাদ",
  taglineEn: "The Authentic Taste of Heritage",
  storyShortBn:
    "বগুড়ার বিখ্যাত মাটির হাঁড়ির দই — প্রজন্মের পর প্রজন্ম ধরে সংরক্ষিত খাঁটি রেসিপি ও আসল স্বাদ।",
  storyShortEn:
    "Bogura's legendary clay-pot yogurt — a heritage recipe and authentic taste preserved through generations.",
  phoneDisplay: "+880 1745-762857",
  phoneRaw: "+8801745762857",
  whatsapp: "8801745762857",
  email: "harirshadbogura@gmail.com",
  addressBn: "শেরপুর রোড, বগুড়া সদর, বগুড়া-৫৮০০, বাংলাদেশ",
  addressEn: "Sherpur Road, Bogura Sadar, Bogura-5800, Bangladesh",
  facebook: "https://facebook.com/harirshad",
  facebookPage: "হাঁড়ির স্বাদ - Taste of Bogura",
  instagram: "https://instagram.com/harirshad",
  businessHoursBn: "প্রতিদিন সকাল ৮টা থেকে রাত ১০টা",
  businessHoursEn: "Every day, 8:00 AM - 10:00 PM",
  mapsEmbed:
    "https://www.google.com/maps?q=Bogura+Sadar,+Bogura,+Bangladesh&output=embed",
  mapsLink: "https://maps.google.com/?q=Bogura+Sadar,+Bogura,+Bangladesh",
  establishmentYear: 1987,
  districtsServed: 64,
  customers: 12000,
};

export const delivery = {
  insideDhaka: 80,
  outsideDhaka: 120,
  freeOver: 1000,
  leadTimeBn: "ঢাকার ভেতরে ২৪–৪৮ ঘণ্টা, ঢাকার বাইরে ২–৪ দিন",
  leadTimeEn: "24-48h inside Dhaka, 2-4 days outside Dhaka",
};

export const coupons: Coupon[] = [
  { code: "HARIR10", type: "percent", value: 10, minAmount: 500 },
  { code: "FREE50", type: "flat", value: 50, minAmount: 300 },
];

export const districts: string[] = [
  "বগুড়া",
  "ঢাকা",
  "চট্টগ্রাম",
  "রাজশাহী",
  "খুলনা",
  "সিলেট",
  "বরিশাল",
  "রংপুর",
  "ময়মনসিংহ",
  "দিনাজপুর",
  "নওগাঁ",
  "জয়পুরহাট",
  "নাটোর",
  "পাবনা",
  "সিরাজগঞ্জ",
  "কুমিল্লা",
  "নরসিংদী",
  "গাজীপুর",
  "নারায়ণগঞ্জ",
  "টাঙ্গাইল",
  "ফরিদপুর",
  "মাদারীপুর",
  "গোপালগঞ্জ",
  "রাজবাড়ী",
  "শরীয়তপুর",
  "মানিকগঞ্জ",
  "মুন্সীগঞ্জ",
  "কিশোরগঞ্জ",
  "নেত্রকোণা",
  "শেরপুর",
  "জামালপুর",
  "ব্রাহ্মণবাড়িয়া",
  "চাঁদপুর",
  "লক্ষ্মীপুর",
  "ফেনী",
  "নোয়াখালী",
  "খাগড়াছড়ি",
  "রাঙ্গামাটি",
  "বান্দরবান",
  "কক্সবাজার",
  "যশোর",
  "সাতক্ষীরা",
  "কুষ্টিয়া",
  "মেহেরপুর",
  "চুয়াডাঙ্গা",
  "ঝিনাইদহ",
  "মাগুরা",
  "নড়াইল",
  "বাগেরহাট",
  "পিরোজপুর",
  "ভোলা",
  "পটুয়াখালী",
  "ঝালকাঠি",
  "পঞ্চগড়",
  "ঠাকুরগাঁও",
  "নীলফামারী",
  "লালমনিরহাট",
  "কুড়িগ্রাম",
  "গাইবান্ধা",
  "সুনামগঞ্জ",
  "হবিগঞ্জ",
  "মৌলভীবাজার",
  "ফুলবাড়ী",
  "বিরামপুর",
  "তাহিরপুর",
];
